### ISSUE TITLE
ValueError at the "write embeddings [stage 3]" step for RNA

### ISSUE THREAD

**Issue by Sebdumas** [SydneyBioX/scJoint#4]
Hello, 

I am running scJoint on unpaired scRNA-seq and scATAC-seq data for label transfer from RNA to ATAC modalities. I get all the output correctly except for the RNA_embeddings because of the error below when running main.py : 

"Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main()
  File "main.py", line 47, in main
    model_stage3.write_embeddings()
  File "/Analysis/ATAC/scJoint/util/trainingprocess_stage3.py", line 210, in write_embeddings
    rna_embedding = rna_embedding / norm(rna_embedding, axis=1, keepdims=True)
  File "/anaconda3/lib/python3.8/site-packages/scipy/linalg/misc.py", line 140, in norm
    a = np.asarray_chkfinite(a)
  File "/anaconda3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs"

Can you please help with that error ? 

Thank you, 

Kind regards,
Sébastien

**Comment by Sebdumas** [comment]
I solved that issue decreasing learning rate for stage 3 in `config.py` from `0.01` to `0.001`. 
I close it. 

Sébastien
