### ISSUE TITLE
CUDA error in stage 3

### ISSUE THREAD

**Issue by ccshao** [SydneyBioX/scJoint#7]
Hi scJoint team,

In our projects the scJoint worked smoothly in the stage 1 and 2, but threw error on the stage3. 
It appeard to me that the all of the loss value are getting incredibly large. 

Many thanks for your insights!

Following are the output for stage 3:
```

Training start [Stage3]
num_workers: 0
load npz matrix: /home/shao/Desktop/Projects/X/10x_ATACseq/scJoint/data_hp_wt/wt_hp_rna.npz
load npz matrix: /home/shao/Desktop/Projects/X/10x_ATACseq/scJoint/data_hp_wt/wt_hp_atac.npz
Epoch: 0
LR is set to 0.01
LR is set to 0.01
 [============ 29/29 =========>.]    Step: 157ms | Tot: 4s393ms | encoding_loss: 12.817, rna_loss: 59.222, center_loss: 5.881
Epoch: 1
 [============ 29/29 =========>.]    Step: 156ms | Tot: 4s366ms | encoding_loss: 919.316, rna_loss: 27529.147, center_loss: 120.546
Epoch: 2
 [================ 29/29 =====>.]    Step: 158ms | Tot: 4s339ms | encoding_loss: 11958.841, rna_loss: 204954.188, center_loss: 413.1Epoch: 3
 [=================== 29/29 ==>.]    Step: 156ms | Tot: 4s349ms | encoding_loss: 260700.759, rna_loss: 7364164.912, center_loss: 254Epoch: 4
 [========================== 29/29   Step: 158ms | Tot: 4s335ms | encoding_loss: 137907357.234, rna_loss: 5798996849.379, center_losEpoch: 5.433
 [============================>.] 29/29 p: 156ms | Tot: 4s368ms | encoding_loss: 25037452131.310, rna_loss: 874840569008.552, centerEpoch: 658529.145
 [============================>.]    Step:  29/29  Tot: 4s324ms | encoding_loss: 104636323585765.516, rna_loss: 3276948089484535.000Epoch: 7_loss: 34642031.474
 [============================>.]    Step: 157 29/29 t: 4s347ms | encoding_loss: 2187132071060303.500, rna_loss: 73972744484661184.0Epoch: 8er_loss: 203889508.828
 [============================>.]    Step: 158ms | T 29/29 02ms | encoding_loss: 972514208877650816.000, rna_loss: 46906742034446524Epoch: 9 center_loss: 4715636888.276
 [============================>.]    Step: 157ms | Tot: 4s3 29/29 encoding_loss: 361596709780774846464.000, rna_loss: 11707894052183Epoch: 10.000, center_loss: 68285345968.552
 [============================>.]    Step: 157ms | Tot: 4s388ms  29/29 ing_loss: 32664000407402539122688.000, rna_loss: 143521479561Epoch: 112480.000, center_loss: 123240449412.414
 [============================>.]    Step: 159ms | Tot: 4s444ms | en 29/29 loss: 8485904532940365594886144.000, rna_loss: 3706595062Epoch: 1209562368.000, center_loss: 125000001182.897
 [============================>.]    Step: 160ms | Tot: 4s436ms | encodin 29/29  1186645034441254863890284544.000, rna_loss: 4430101Epoch: 131753024004096.000, center_loss: 125000002877.793
 [============================>.]    Step: 160ms | Tot: 4s479ms | encoding_los 29/29 50627509908939357502308352.000, rna_loss: 43719Epoch: 14617924641928249344.000, center_loss: 125000002595.310
 [============================>.]    Step: 159ms | Tot: 4s428ms | encoding_loss: 745 29/29 26601367427467389698048.000, rna_loss: 23Epoch: 15674412783426934507831296.000, center_loss: 125000002312.828
 [============ 29/29 =========>.]    Step: 159ms | Tot: 4s458ms | encoding_loss: inf, rna_loss: inf, center_loss: nan               Epoch: 16er_loss: 125000001536.000 000, center_loss: 125000000853.333
Traceback (most recent call last):   Step: 161ms | Tot: 2s89ms | encoding_loss: inf, rna_loss: nan, center_loss: nan
  File "main.py", line 56, in <module>
    main()
  File "main.py", line 44, in main
    model_stage3.train(epoch)
  File "/home/shao/Desktop/Projects/X/10x_ATACseq/scJoint/util/trainingprocess_stage3.py", line 152, in train
    encoding_loss.backward(retain_graph=True)
  File "/home/shao/miniconda3/envs/env_scjoint/lib/python3.8/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/shao/miniconda3/envs/env_scjoint/lib/python3.8/site-packages/torch/autograd/__init__.py", line 97, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: device-side assert triggered
```

Stage 1 and knn worked fine
```
Start time:  09:20:49
Training start [Stage1]
num_workers: 0
load npz matrix: /home/shao/Desktop/Projects/X/10x_ATACseq/scJoint/data_hp_wt/wt_hp_rna.npz
load npz matrix: /home/shao/Desktop/Projects/X/10x_ATACseq/scJoint/data_hp_wt/wt_hp_atac.npz
Epoch: 0
LR is set to 0.01
LR is set to 0.01
 [============ 29/29 =========>.]    Step: 152ms | Tot: 4s236ms | encoding_loss: 5.734, rna_loss: 1.521
Epoch: 1
 [============ 29/29 =========>.]    Step: 154ms | Tot: 4s270ms | encoding_loss: 3.825, rna_loss: 0.552
Epoch: 2
 [============ 29/29 =========>.]    Step: 152ms | Tot: 4s250ms | encoding_loss: 3.643, rna_loss: 0.281
Epoch: 3
 [============ 29/29 =========>.]    Step: 155ms | Tot: 4s256ms | encoding_loss: 3.586, rna_loss: 0.172
Epoch: 4
 [============ 29/29 =========>.]    Step: 157ms | Tot: 4s297ms | encoding_loss: 3.541, rna_loss: 0.128
Epoch: 5
 [============ 29/29 =========>.]    Step: 154ms | Tot: 4s283ms | encoding_loss: 3.507, rna_loss: 0.091
Epoch: 6
 [============ 29/29 =========>.]    Step: 155ms | Tot: 4s290ms | encoding_loss: 3.483, rna_loss: 0.075
Epoch: 7
 [============ 29/29 =========>.]    Step: 153ms | Tot: 4s256ms | encoding_loss: 3.462, rna_loss: 0.057
Epoch: 8
 [============ 29/29 =========>.]    Step: 155ms | Tot: 4s303ms | encoding_loss: 3.454, rna_loss: 0.044
Epoch: 9
 [============ 29/29 =========>.]    Step: 156ms | Tot: 4s327ms | encoding_loss: 3.435, rna_loss: 0.038
Epoch: 10
 [============ 29/29 =========>.]    Step: 156ms | Tot: 4s351ms | encoding_loss: 3.426, rna_loss: 0.032
Epoch: 11
 [============ 29/29 =========>.]    Step: 162ms | Tot: 4s337ms | encoding_loss: 3.410, rna_loss: 0.027
Epoch: 12
 [============ 29/29 =========>.]    Step: 160ms | Tot: 4s334ms | encoding_loss: 3.399, rna_loss: 0.026
Epoch: 13
 [============ 29/29 =========>.]    Step: 159ms | Tot: 4s356ms | encoding_loss: 3.382, rna_loss: 0.022
Epoch: 14
 [============ 29/29 =========>.]    Step: 155ms | Tot: 4s311ms | encoding_loss: 3.370, rna_loss: 0.019
Epoch: 15
 [============ 29/29 =========>.]    Step: 155ms | Tot: 4s313ms | encoding_loss: 3.363, rna_loss: 0.017
Epoch: 16
 [============ 29/29 =========>.]    Step: 153ms | Tot: 4s284ms | encoding_loss: 3.347, rna_loss: 0.016
Epoch: 17
 [============ 29/29 =========>.]    Step: 152ms | Tot: 4s295ms | encoding_loss: 3.338, rna_loss: 0.015
Epoch: 18
 [============ 29/29 =========>.]    Step: 153ms | Tot: 4s305ms | encoding_loss: 3.339, rna_loss: 0.014
Epoch: 19
 [============ 29/29 =========>.]    Step: 154ms | Tot: 4s319ms | encoding_loss: 3.331, rna_loss: 0.014
Write embeddings
 [============ 26/26 =========>.]    Step: 40ms | Tot: 2s639ms | write embeddings and predictions for db:wt_hp_rna
 [============ 30/30 ==========>]    Step: 48ms | Tot: 3s94ms | write embeddings and predictions for db:wt_hp_atac
Stage 1 finished:  09:22:28
KNN
[KNN] Read RNA data
[KNN] Read ATAC data
[KNN] Build Space
[KNN] knn
KNN finished:  09:22:30
```

**Comment by YingxinLin** [comment]
Hi,

Thank you for your interest in scJoint. I noticed that the loss values have exploded in stage 3 in your case. Maybe you can try to reduce the learning rate or increase the batch size in stage 3 to see if the loss function can converge.

Yingxin

**Comment by ccshao** [comment]
Worked with .001 learning rate and 512 batch size in srtage 3.
